name: Get latest yara-python version

on:
  schedule:
    - cron:  '0 12 * * *'
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Fetch release version
        run: |
          LATEST=$(curl -sL https://api.github.com/repos/VirusTotal/yara-python/releases/latest | jq -r ".tag_name")
          if [[ $LATEST > $(cat VERSION) ]]; then
            echo $LATEST > VERSION
          fi

      - name: Update README.rst
        run: |
          sed -i -E "s/version: \*\*.+\*\*/version: **`cat VERSION`**/" README.rst

      - name: Check for modified files
        id: git-check
        run: echo "modified=$(([ -z "`git status --porcelain`" ] || [ "`git ls-remote --heads origin update-$(cat VERSION)`" ] && echo "false") || echo "true")" >> $GITHUB_OUTPUT

      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Schamper'
          git config --global user.email '1254028+Schamper@users.noreply.github.com'
          git checkout -b update-`cat VERSION`
          git commit -am "Update to version `cat VERSION`"
          git push -u origin update-`cat VERSION`

          gh pr create -B main -H update-`cat VERSION` --fill
        env:
          GH_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
